version: '3'
services:
    squid:
        container_name: squid
        hostname: squid
        image: ubuntu/squid
        restart: unless-stopped
        volumes:
            - ./squid.conf:/etc/squid/squid.conf
        ports:
            - 3128:3128
        networks:
            - squid
networks:
    squid:
        name: squid
