version: "3"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: mememe
      POSTGRES_PASSWORD: myHorriblePassword
      POSTGRES_DB: testdatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  react-app:
    image: countryapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
