version: "3.9"
services:
  nuclear-api:
    build: .
    restart: always
    stop_signal: SIGINT
    ports:
      - 80:5000
    networks:
      server14net1:
        ipv4_address: 192.168.154.3
networks:
  server14net2:
    name: server14net2
    driver: macvlan
    driver_opts:
      parent: ens5
    ipam:
      driver: default
      config:
        - subnet: 192.168.154.0/24
          gateway: 192.168.154.1
