version: "3.9"
services:
  minecraft-server:
    build: .
    restart: always
    environment:
      - MINECRAFT_MEMORY=2G
    ports:
      - 25565:25565
    volumes:
      - data:/minecraft
    networks:
      - server14net
volumes:
  data:
